### ISSUE TITLE
Cant flash geekboards macropad v2 with hex file via QMK Toolbox

### ISSUE THREAD

**Issue by tony-sol** [arduxio/qmk-ardux#5]
Related issue in QMK Toolbox (https://github.com/qmk/qmk_toolbox/issues/372)

As well as geekboards/macropad_2 is an STM32F072 board, it needs a .bin file to be flashed via QMK Toolbox which is recommended by README here.

Is there any way to flash macropad for artsey?

**Comment by mcrosson** [comment]
we are investigating proper arm support and will report back when we have more info

we are also over on discord at https://discord.gg/7XNfN95JMM if youd like to track any live conversation related to this

**Comment by mcrosson** [comment]
research notes

- this likely needs an ifdef for the mcu/loader selection so it auto-grabs the defaults from the geekboards keyboard folder
- build docs show what looks like an integrated mcu
- this should be setup as a static / non overridden mcu/loader setup
- update github build+release rules to use bin instead of hex
